package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Switches every entity's id generation from IDENTITY to a pooled SEQUENCE
 * (allocationSize=50 on each entity's own @SequenceGenerator) - see
 * biblioteca-server/README.md's "Bugs & performance debt" for the
 * diagnosis: IDENTITY categorically defeats Hibernate's JDBC insert
 * batching (jdbc.batch_size=100 was configured but silently inert),
 * because a generated key has to come back immediately after each
 * individual insert. A SEQUENCE with allocationSize>1 lets Hibernate's
 * "pooled" optimizer grab a whole block of ids from one query and hand
 * them out locally, which is what actually makes batching possible.
 *
 * No column DDL changes here - Derby's IDENTITY columns here were always
 * declared "GENERATED BY DEFAULT AS IDENTITY" (confirmed via Hibernate's
 * own DerbyDialect, which reuses DB2IdentityColumnSupport), not "GENERATED
 * ALWAYS", so they already accept an explicit value in an INSERT instead
 * of demanding to generate their own. Hibernate just starts supplying one
 * (fetched from the new sequence) going forward; the column's own identity
 * counter becomes unused, harmlessly.
 *
 * One sequence per table, named "<table>_seq" (matching each entity's
 * @SequenceGenerator(sequenceName=...)), seeded to start strictly above
 * that table's current max id so a freshly generated id can never collide
 * with a row IDENTITY already assigned - safe against a populated database
 * as well as an empty one (an empty table simply starts its sequence at 1,
 * identical to what a fresh IDENTITY column would have produced anyway).
 * INCREMENT BY matches allocationSize exactly - required for Hibernate's
 * pooled optimizer to hand out that many ids per fetched block correctly.
 *
 * A table that doesn't exist yet (this runs before Hibernate's
 * ddl-auto=update creates anything - see FlywayConfig) is skipped rather
 * than failing: on a genuinely fresh database every table is skipped here,
 * and ddl-auto=update creates both the (identity-free) table and its
 * missing sequence itself once it sees the entity mapping, same "fresh
 * databases are left alone" reasoning as V1.
 */
public class V2__Switch_identity_columns_to_pooled_sequences extends BaseJavaMigration {

    private static final int ALLOCATION_SIZE = 50;

    // table -> sequence name, one per entity now using
    // @GeneratedValue(strategy = SEQUENCE).
    private static final Map<String, String> SEQUENCES_BY_TABLE = new LinkedHashMap<>();
    static {
        SEQUENCES_BY_TABLE.put("tei_file", "tei_file_seq");
        SEQUENCES_BY_TABLE.put("tei_elem", "tei_elem_seq"); // shared with TeiDiv (SINGLE_TABLE inheritance)
        SEQUENCES_BY_TABLE.put("author", "author_seq");
        SEQUENCES_BY_TABLE.put("app_user", "app_user_seq");
        SEQUENCES_BY_TABLE.put("reading_progress", "reading_progress_seq");
        SEQUENCES_BY_TABLE.put("div_collection", "div_collection_seq");
        SEQUENCES_BY_TABLE.put("div_collection_item", "div_collection_item_seq");
        SEQUENCES_BY_TABLE.put("div_media", "div_media_seq");
        SEQUENCES_BY_TABLE.put("author_media", "author_media_seq");
        SEQUENCES_BY_TABLE.put("opus_vectorizing_stat", "opus_vectorizing_stat_seq");
        SEQUENCES_BY_TABLE.put("embedding_batch_stat", "embedding_batch_stat_seq");
    }

    @Override
    public void migrate(Context context) throws Exception {
        for (Map.Entry<String, String> entry : SEQUENCES_BY_TABLE.entrySet()) {
            final String table = entry.getKey();
            final String sequence = entry.getValue();
            if (!tableExists(context, table))
                continue;
            if (sequenceExists(context, sequence))
                continue;

            final long startWith = maxId(context, table) + 1;
            try (Statement statement = context.getConnection().createStatement()) {
                statement.execute("CREATE SEQUENCE " + sequence
                        + " START WITH " + startWith
                        + " INCREMENT BY " + ALLOCATION_SIZE);
            }
        }
    }

    private static boolean tableExists(Context context, String table) throws Exception {
        final DatabaseMetaData metadata = context.getConnection().getMetaData();
        try (ResultSet result = metadata.getTables(null, null, table.toUpperCase(Locale.ROOT), null)) {
            if (result.next()) return true;
        }
        try (ResultSet result = metadata.getTables(null, null, table, null)) {
            return result.next();
        }
    }

    // Idempotency guard, not expected to trigger in practice (Flyway
    // migrations only ever run once) - cheap insurance against a
    // hand-run/retry scenario creating the same sequence twice. Sequences
    // aren't "tables", so DatabaseMetaData.getTables can't see them -
    // Derby exposes them via its own SYS.SYSSEQUENCES system catalog.
    private static boolean sequenceExists(Context context, String sequence) throws Exception {
        try (var statement = context.getConnection().prepareStatement(
                "SELECT 1 FROM SYS.SYSSEQUENCES WHERE UPPER(SEQUENCENAME) = ?")) {
            statement.setString(1, sequence.toUpperCase(Locale.ROOT));
            try (ResultSet result = statement.executeQuery()) {
                return result.next();
            }
        }
    }

    private static long maxId(Context context, String table) throws Exception {
        try (Statement statement = context.getConnection().createStatement();
             ResultSet result = statement.executeQuery("SELECT MAX(id) FROM " + table)) {
            result.next();
            return result.getLong(1); // JDBC returns 0 for SQL NULL (empty table)
        }
    }
}
